import React from 'react';

// Original Tattoo Flash & Artworks Catalog with authentic high-resolution studio assets
export const TATTOO_ARTWORKS_CATALOG = [
  {
    id: 'mahadev-trishul',
    _id: 'mahadev-trishul',
    name: 'Sacred Mahadev Trishul & Damru',
    artist: 'Master Sunil',
    artistTitle: 'Certified Master Tattooist',
    style: 'Sacred Devbhoomi',
    description: 'Iconic Lord Shiva Trishul trident with Damru drum, Crescent Moon, and Sacred Om stippling.',
    estTime: '3.5 hrs',
    difficulty: 'Masterpiece',
    previewImage: '/images/tattoos/mahadev_trishul.jpg',
    dataUri: '/images/tattoos/mahadev_trishul.jpg',
    bodyAreas: ['Forearm', 'Chest', 'Upper Arm', 'Back', 'Spine'],
    isDefaultReference: true,
  },
  {
    id: 'om-shiva-calligraphy',
    _id: 'om-shiva-calligraphy',
    name: 'Om Namah Shivaya Sanskrit Mandala',
    artist: 'Master Sunil',
    artistTitle: 'Certified Master Tattooist',
    style: 'Sacred Devbhoomi',
    description: 'Sacred Trishul with Devanagari Sanskrit mantra calligraphy and radiant stippled sunburst rays.',
    estTime: '3.0 hrs',
    difficulty: 'Masterpiece',
    previewImage: '/images/tattoos/om_shiva_calligraphy.jpg',
    dataUri: '/images/tattoos/om_shiva_calligraphy.jpg',
    bodyAreas: ['Forearm', 'Chest', 'Spine', 'Upper Arm', 'Neck'],
    isDefaultReference: true,
  },
  {
    id: 'japanese-dragon-koi',
    _id: 'japanese-dragon-koi',
    name: 'Ryu Dragon Koi Leaping Waves',
    artist: 'Master Sunil',
    artistTitle: 'Certified Master Tattooist',
    style: 'Japanese',
    description: 'Dynamic Japanese traditional dragon koi fish ascending swirling tidal waves with sharp scales and fin details.',
    estTime: '4.5 hrs',
    difficulty: 'Complex',
    previewImage: '/images/tattoos/japanese_koi.jpg',
    dataUri: '/images/tattoos/japanese_koi.jpg',
    bodyAreas: ['Forearm', 'Upper Arm', 'Thigh', 'Calf', 'Back', 'Shoulder'],
    isDefaultReference: true,
  },
  {
    id: 'phoenix-rising-flame',
    _id: 'phoenix-rising-flame',
    name: 'Phoenix Rising From Sacred Flames',
    artist: 'Master Sunil',
    artistTitle: 'Certified Master Tattooist',
    style: 'Blackwork',
    description: 'Majestic mythical phoenix bird spreading ornate dotwork wings emerging from eternal fire.',
    estTime: '4.0 hrs',
    difficulty: 'Masterpiece',
    previewImage: '/images/tattoos/phoenix_flame.jpg',
    dataUri: '/images/tattoos/phoenix_flame.jpg',
    bodyAreas: ['Back', 'Chest', 'Shoulder', 'Thigh', 'Ribs', 'Calf'],
    isDefaultReference: true,
  },
  {
    id: 'celtic-howling-wolf',
    _id: 'celtic-howling-wolf',
    name: 'Nordic Howling Wolf & Moon',
    artist: 'Master Sunil',
    artistTitle: 'Certified Master Tattooist',
    style: 'Geometric',
    description: 'Intricate Celtic knotwork howling wolf with celestial crescent moon, runes, and sacred geometry.',
    estTime: '3.5 hrs',
    difficulty: 'Intermediate',
    previewImage: '/images/tattoos/celtic_wolf.jpg',
    dataUri: '/images/tattoos/celtic_wolf.jpg',
    bodyAreas: ['Forearm', 'Upper Arm', 'Calf', 'Thigh', 'Back', 'Shoulder'],
    isDefaultReference: true,
  },
  {
    id: 'butterfly-botanical-flora',
    _id: 'butterfly-botanical-flora',
    name: 'Fine Line Butterfly & Botanical Lavender',
    artist: 'Master Sunil',
    artistTitle: 'Certified Master Tattooist',
    style: 'Fine Line',
    description: 'Delicate half-butterfly morphing into blooming wild daisies, lavender sprigs, and stardust.',
    estTime: '2.0 hrs',
    difficulty: 'Delicate',
    previewImage: '/images/tattoos/butterfly_botanical.jpg',
    dataUri: '/images/tattoos/butterfly_botanical.jpg',
    bodyAreas: ['Wrist', 'Ankle', 'Neck', 'Forearm', 'Shoulder'],
    isDefaultReference: true,
  },
  {
    id: 'nautical-compass-mountains',
    _id: 'nautical-compass-mountains',
    name: 'Himalayan Compass & Arrow Navigator',
    artist: 'Master Sunil',
    artistTitle: 'Certified Master Tattooist',
    style: 'Geometric',
    description: 'Sacred compass rose with Himalayan mountain peaks, celestial constellations, and warrior arrows.',
    estTime: '3.0 hrs',
    difficulty: 'Intermediate',
    previewImage: '/images/tattoos/compass_navigation.jpg',
    dataUri: '/images/tattoos/compass_navigation.jpg',
    bodyAreas: ['Forearm', 'Shoulder', 'Calf', 'Wrist', 'Upper Arm'],
    isDefaultReference: true,
  },
  {
    id: 'una-moon-flora',
    _id: 'una-moon-flora',
    name: 'Minimalist Moon & Wild Flora',
    artist: 'Master Sunil',
    artistTitle: 'Certified Master Tattooist',
    style: 'Fine Line',
    description: 'Delicate crescent moon with wild botanical flowers, leaves, and celestial stardust.',
    estTime: '2.0 hrs',
    difficulty: 'Delicate',
    previewImage: '/images/tattoos/moon_flora.jpg',
    dataUri: '/images/tattoos/moon_flora.jpg',
    bodyAreas: ['Forearm', 'Wrist', 'Ankle', 'Shoulder', 'Neck'],
    isDefaultReference: true,
  },
  {
    id: 'una-fine-serpent',
    _id: 'una-fine-serpent',
    name: 'Fine Line Serpent & Peony',
    artist: 'Master Sunil',
    artistTitle: 'Certified Master Tattooist',
    style: 'Fine Line',
    description: 'Coiled serpent snake with detailed scales wrapped around blooming peony flowers.',
    estTime: '3.0 hrs',
    difficulty: 'Intermediate',
    previewImage: '/images/tattoos/serpent_peony.jpg',
    dataUri: '/images/tattoos/serpent_peony.jpg',
    bodyAreas: ['Forearm', 'Upper Arm', 'Spine', 'Thigh', 'Ribs'],
    isDefaultReference: true,
  },
  {
    id: 'una-lotus-geometry',
    _id: 'una-lotus-geometry',
    name: 'Devbhoomi Sacred Lotus & Unalome',
    artist: 'Master Sunil',
    artistTitle: 'Certified Master Tattooist',
    style: 'Sacred Devbhoomi',
    description: 'Sacred unalome lotus bloom with dotwork mandala petals and vertical chakra alignment.',
    estTime: '2.5 hrs',
    difficulty: 'Delicate',
    previewImage: '/images/tattoos/sacred_lotus.jpg',
    dataUri: '/images/tattoos/sacred_lotus.jpg',
    bodyAreas: ['Spine', 'Neck', 'Upper Arm', 'Back', 'Wrist', 'Ankle'],
    isDefaultReference: true,
  },
  {
    id: 'mark-geom-lion',
    _id: 'mark-geom-lion',
    name: 'Geometric Lion King & Mountain',
    artist: 'Master Sunil',
    artistTitle: 'Certified Master Tattooist',
    style: 'Geometric',
    description: 'Polygonal sacred geometry royal lion head with Himalayan mountain peak line art.',
    estTime: '3.5 hrs',
    difficulty: 'Complex',
    previewImage: '/images/tattoos/geometric_lion.jpg',
    dataUri: '/images/tattoos/geometric_lion.jpg',
    bodyAreas: ['Chest', 'Upper Arm', 'Back', 'Shoulder', 'Thigh'],
    isDefaultReference: true,
  },
  {
    id: 'mark-sacred-mandala',
    _id: 'mark-sacred-mandala',
    name: 'Devbhoomi Sacred Radial Mandala',
    artist: 'Master Sunil',
    artistTitle: 'Certified Master Tattooist',
    style: 'Mandala',
    description: 'Intricate radial sacred geometry mandala with fine dotwork pointillism.',
    estTime: '4.5 hrs',
    difficulty: 'Masterpiece',
    previewImage: '/images/tattoos/sacred_mandala.jpg',
    dataUri: '/images/tattoos/sacred_mandala.jpg',
    bodyAreas: ['Back', 'Shoulder', 'Chest', 'Thigh', 'Ribs'],
    isDefaultReference: true,
  },
  {
    id: 'eliza-trad-rose',
    _id: 'eliza-trad-rose',
    name: 'Himalayan Sacred Botanical Rose',
    artist: 'Master Sunil',
    artistTitle: 'Certified Master Tattooist',
    style: 'Traditional',
    description: 'Blooming classical botanical rose with delicate petals and fine-line thorns.',
    estTime: '2.5 hrs',
    difficulty: 'Intermediate',
    previewImage: '/images/tattoos/sacred_rose.jpg',
    dataUri: '/images/tattoos/sacred_rose.jpg',
    bodyAreas: ['Shoulder', 'Forearm', 'Ankle', 'Wrist', 'Neck', 'Ribs'],
    isDefaultReference: true,
  },
  {
    id: 'liam-gothic-skull',
    _id: 'liam-gothic-skull',
    name: 'Gothic Obsidian Skull Filigree',
    artist: 'Master Sunil',
    artistTitle: 'Certified Master Tattooist',
    style: 'Blackwork',
    description: 'Detailed blackwork human skull with ornate baroque filigree ornamentation and dark depth.',
    estTime: '4.0 hrs',
    difficulty: 'Complex',
    previewImage: '/images/tattoos/gothic_skull.jpg',
    dataUri: '/images/tattoos/gothic_skull.jpg',
    bodyAreas: ['Upper Arm', 'Chest', 'Back', 'Calf'],
    isDefaultReference: true,
  },
  {
    id: 'liam-neo-dagger',
    _id: 'liam-neo-dagger',
    name: 'Devbhoomi Trishul Dagger Heart',
    artist: 'Master Sunil',
    artistTitle: 'Certified Master Tattooist',
    style: 'Neo-Traditional',
    description: 'Ornate sacred Trishul sword dagger piercing sacred heart with radiant sacred geometry.',
    estTime: '3.5 hrs',
    difficulty: 'Intermediate',
    previewImage: '/images/tattoos/trishul_dagger.jpg',
    dataUri: '/images/tattoos/trishul_dagger.jpg',
    bodyAreas: ['Forearm', 'Calf', 'Spine', 'Ribs', 'Upper Arm'],
    isDefaultReference: true,
  },
];
