import React from 'react';

// Original Tattoo Flash & Artworks Catalog mapped with authentic images
export const TATTOO_ARTWORKS_CATALOG = [
  {
    id: 'mahadev-trishul',
    _id: 'mahadev-trishul',
    name: 'Sacred Mahadev Trishul & Damru',
    artist: 'Master Sunil',
    artistTitle: 'Certified Master Tattooist',
    style: 'Sacred Devbhoomi',
    description: 'Iconic Lord Shiva Trishul trident with Damru drum, Crescent Moon, and Sacred Om stippling.',
    estTime: '3.5 hrs',
    difficulty: 'Masterpiece',
    previewImage: '/images/tattoos/mahadev_trishul.jpg',
    dataUri: '/images/tattoos/mahadev_trishul.jpg',
    bodyAreas: ['Forearm', 'Chest', 'Upper Arm', 'Back', 'Spine'],
    isDefaultReference: true,
  },
  {
    id: 'una-moon-flora',
    _id: 'una-moon-flora',
    name: 'Minimalist Moon & Flora',
    artist: 'Master Sunil',
    artistTitle: 'Certified Master Tattooist',
    style: 'Minimalist',
    description: 'Delicate crescent moon with wild botanical flowers, leaves, and celestial stardust.',
    estTime: '2.0 hrs',
    difficulty: 'Delicate',
    previewImage: '/images/tattoos/moon_flora.jpg',
    dataUri: '/images/tattoos/moon_flora.jpg',
    bodyAreas: ['Forearm', 'Wrist', 'Ankle', 'Shoulder'],
    isDefaultReference: true,
  },
  {
    id: 'una-fine-serpent',
    _id: 'una-fine-serpent',
    name: 'Fine Line Serpent & Peony',
    artist: 'Master Sunil',
    artistTitle: 'Certified Master Tattooist',
    style: 'Fine Line',
    description: 'Coiled serpent snake with detailed scales wrapped around blooming peony flowers.',
    estTime: '3.0 hrs',
    difficulty: 'Intermediate',
    previewImage: '/images/tattoos/serpent_peony.jpg',
    dataUri: '/images/tattoos/serpent_peony.jpg',
    bodyAreas: ['Forearm', 'Upper Arm', 'Spine', 'Thigh'],
    isDefaultReference: true,
  },
  {
    id: 'una-lotus-geometry',
    _id: 'una-lotus-geometry',
    name: 'Devbhoomi Sacred Lotus',
    artist: 'Master Sunil',
    artistTitle: 'Certified Master Tattooist',
    style: 'Sacred Devbhoomi',
    description: 'Sacred unalome lotus bloom with dotwork mandala petals and vertical chakra alignment.',
    estTime: '2.5 hrs',
    difficulty: 'Delicate',
    previewImage: '/images/tattoos/sacred_lotus.jpg',
    dataUri: '/images/tattoos/sacred_lotus.jpg',
    bodyAreas: ['Spine', 'Neck', 'Upper Arm', 'Back', 'Wrist'],
    isDefaultReference: true,
  },
  {
    id: 'mark-geom-lion',
    _id: 'mark-geom-lion',
    name: 'Geometric Lion & Mountain',
    artist: 'Master Sunil',
    artistTitle: 'Certified Master Tattooist',
    style: 'Geometric',
    description: 'Polygonal sacred geometry royal lion head with Himalayan mountain peak line art.',
    estTime: '3.5 hrs',
    difficulty: 'Complex',
    previewImage: '/images/tattoos/geometric_lion.jpg',
    dataUri: '/images/tattoos/geometric_lion.jpg',
    bodyAreas: ['Chest', 'Upper Arm', 'Back', 'Shoulder', 'Thigh'],
    isDefaultReference: true,
  },
  {
    id: 'mark-sacred-mandala',
    _id: 'mark-sacred-mandala',
    name: 'Devbhoomi Sacred Mandala',
    artist: 'Master Sunil',
    artistTitle: 'Certified Master Tattooist',
    style: 'Mandala',
    description: 'Intricate radial sacred geometry mandala with fine dotwork pointillism.',
    estTime: '4.5 hrs',
    difficulty: 'Masterpiece',
    previewImage: '/images/tattoos/sacred_mandala.jpg',
    dataUri: '/images/tattoos/sacred_mandala.jpg',
    bodyAreas: ['Back', 'Shoulder', 'Chest', 'Thigh', 'Ribs'],
    isDefaultReference: true,
  },
  {
    id: 'eliza-trad-rose',
    _id: 'eliza-trad-rose',
    name: 'Himalayan Sacred Rose',
    artist: 'Master Sunil',
    artistTitle: 'Certified Master Tattooist',
    style: 'Traditional',
    description: 'Blooming classical botanical rose with delicate petals and fine-line thorns.',
    estTime: '2.5 hrs',
    difficulty: 'Intermediate',
    previewImage: '/images/tattoos/sacred_rose.jpg',
    dataUri: '/images/tattoos/sacred_rose.jpg',
    bodyAreas: ['Shoulder', 'Forearm', 'Ankle', 'Wrist', 'Neck'],
    isDefaultReference: true,
  },
  {
    id: 'liam-gothic-skull',
    _id: 'liam-gothic-skull',
    name: 'Gothic Obsidian Skull',
    artist: 'Master Sunil',
    artistTitle: 'Certified Master Tattooist',
    style: 'Blackwork',
    description: 'Detailed blackwork human skull with ornate baroque filigree ornamentation and dark depth.',
    estTime: '4.0 hrs',
    difficulty: 'Complex',
    previewImage: '/images/tattoos/gothic_skull.jpg',
    dataUri: '/images/tattoos/gothic_skull.jpg',
    bodyAreas: ['Upper Arm', 'Chest', 'Back', 'Calf'],
    isDefaultReference: true,
  },
  {
    id: 'liam-neo-dagger',
    _id: 'liam-neo-dagger',
    name: 'Devbhoomi Trishul Dagger',
    artist: 'Master Sunil',
    artistTitle: 'Certified Master Tattooist',
    style: 'Neo-Traditional',
    description: 'Ornate sacred Trishul sword dagger piercing sacred heart with radiant sacred geometry.',
    estTime: '3.5 hrs',
    difficulty: 'Intermediate',
    previewImage: '/images/tattoos/trishul_dagger.jpg',
    dataUri: '/images/tattoos/trishul_dagger.jpg',
    bodyAreas: ['Forearm', 'Calf', 'Spine', 'Ribs'],
    isDefaultReference: true,
  },
];
